### ISSUE TITLE
WHY DELETE MY POST WITH CODE??? 

### ISSUE THREAD

**Issue by Verteletsky** [seejohnrun/haste-client#42]
WHY YOU DELETE MY POST WITH CODE??? LINK: https://hastebin.com/oqukaqeruv.cpp

WHHHAAYYYYYYY????? Its MY WORK!!! YEARS!!!!

**Comment by akien-mga** [comment]
It's probably not deleted, hastebin.com is having technical issues since a couple of weeks and can't be used to post new pastes (and apparently neither to access old ones).

Regardless, pastebin services are not meant for long time conservation of pastes. It's only meant to share text content with others efficiently, without guarantee of expiry date. Actually for hastebin.com you do have a guarantee that it *will* expire after 30 days: https://github.com/seejohnrun/haste-server/blob/master/about.md#duration (also mentioned on https://hastebin.com/about.md but currently inaccessible).

If you want long term conservation of your code, use a git repository, or GitHub Gist/GitLab Snippet.

**Comment by webmastir** [comment]
@Verteletsky  FYI, your Hastebin link is active again.

**Comment by Verteletsky** [comment]
@webmastir Thanks!!!
@akien-mga its a problem, because note, no have 30 days
